// client/src/App.tsx
import { useEffect, FC } from 'react'
import { motion, AnimatePresence, MotionConfig } from 'framer-motion'

import useMediaQuery from '@mui/material/useMediaQuery'
import Sheet from '@mui/joy/Sheet'
import List from '@mui/joy/List'
import ListItem from '@mui/joy/ListItem'

import type Item from './types/Item'

import useStore from './store/useStore'
import ShoppingListItem from './components/ShoppingListItem'
import { webSocketManager } from './WebSocketManager'
import UndoRedoHandler from './components/UndoRedoHandler'

const MotionList = motion(List)
const MotionListItem = motion(ListItem)

interface AppProps {
  items: Item[]
}

const App: FC<AppProps> = ({ items }) => (
  <MotionConfig transition={{ duration: 0.15 }}>
    <AnimatePresence>
      <MotionList layout>
        {items.map((item, i) => (
          <MotionListItem key={item.id} layout>
            <ShoppingListItem
              isOnly={items.length === 1}
              isLast={i === items.length - 1}
              {...item}
            />
          </MotionListItem>
        ))}
      </MotionList>
    </AnimatePresence>
  </MotionConfig>
)

const AppContainer = () => {
  const [{ items, loaded }, dispatch] = useStore()
  const useMobileLayout = useMediaQuery('(max-width:624px)')

  useEffect(() => {
    const wsScheme = window.location.protocol === 'https:' ? 'wss' : 'ws'
    const basePath = window.location.pathname.replace(/\/$/, '')
    const wsUrl = window.location.host.startsWith('localhost')
      ? 'ws://127.0.0.1:1222'
      : `${wsScheme}://${window.location.host}/${basePath}/ws`

    // Connect to WebSocket and pass the dispatch function
    webSocketManager.connect(wsUrl, dispatch)
  }, []) // eslint-disable-line react-hooks/exhaustive-deps

  if (!loaded) {
    return null
  }

  if (useMobileLayout) {
    return <App items={items} />
  }

  return (
    <Sheet
      sx={{
        maxWidth: 600,
        mx: 'auto',
        my: 4,
        py: 3,
        px: 2,
        borderRadius: 'sm',
        boxShadow: 'md',
      }}
      variant="outlined"
    >
      <UndoRedoHandler />
      <App items={items} />
    </Sheet>
  )
}

export default AppContainer

// client-solid/src/App.tsx
import { type Component, For, Show, onMount } from 'solid-js'
import { TransitionGroup } from 'solid-transition-group'
import { createMediaQuery } from '@solid-primitives/media'

import type Item from './store/types/Item'

import useStore from './store/useStore'
import ShoppingListItem from './components/ShoppingListItem'
import WebSocketManager from './WebSocketManager'
import UndoRedoHandler from './components/UndoRedoHandler'

interface ShoppingListProps {
  items: Item[]
}

const ShoppingList: Component<ShoppingListProps> = (props) => (
  <TransitionGroup name="group-item">
    <For each={props.items}>
      {(item, i) => (
        <ShoppingListItem
          isOnly={props.items.length === 1}
          isLast={i() === props.items.length - 1}
          {...item}
        />
      )}
    </For>
  </TransitionGroup>
)

interface AppProps {
  wsm: WebSocketManager
}

const App: Component<AppProps> = (props) => {
  const [state, dispatch] = useStore()
  const useMobileLayout = createMediaQuery('(max-width:624px)')

  onMount(() => {
    const wsScheme = window.location.protocol === 'https:' ? 'wss' : 'ws'
    const basePath = window.location.pathname.replace(/\/$/, '')
    const wsUrl = window.location.host.startsWith('localhost')
      ? 'ws://127.0.0.1:1222'
      : `${wsScheme}://${window.location.host}/${basePath}/ws`

    // Connect to WebSocket and pass the dispatch function
    props.wsm.connect(wsUrl, dispatch)
  })

  return (
    <Show
      when={state.loaded && state.webSocketState === 'connected'}
      fallback={
        <div class="flex items-center justify-center h-screen">
          <div class="loader" />
        </div>
      }
    >
      <div
        class={
          useMobileLayout()
            ? 'py-3 px-1'
            : 'max-w-lg mx-auto my-4 py-3 px-2 rounded-sm shadow-md border'
        }
      >
        <ShoppingList items={state.items} />
      </div>
      <UndoRedoHandler />
    </Show>
  )
}

export default App
